# Generated by Django 3.1.2 on 2020-10-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.DecimalField(blank=True, decimal_places=15, help_text='Longitude Coordinate for Squirrel sighting point', max_digits=20, max_length=50)),
                ('Y', models.DecimalField(blank=True, decimal_places=15, help_text='Latitude Coordinate for Squirrel sighting point', max_digits=20, max_length=50)),
                ('Unique_squirrel_id', models.CharField(help_text='Identification tag for each squirrel sightings', max_length=100, primary_key=True, serialize=False)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Squirrel sighting session occured in morning or afternoon', max_length=100)),
                ('Date', models.DateField(help_text='Session of sighting day and month')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=50)),
                ('Primary_fur_color', models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='fur color', max_length=10)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Where the squirrel was when first sighted', max_length=50)),
                ('Specific_location', models.CharField(blank=True, help_text='Sighters occasional comment on the squirrel location', max_length=200)),
                ('Running', models.BooleanField(default=False, help_text='Squirrel was seen running')),
                ('Chasing', models.BooleanField(default=False, help_text='Squirrel was seen chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Squirrel was seen climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Squirrel was seen eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Squirrel was seen foraging for food')),
                ('Other_activities', models.CharField(blank=True, help_text='no description available ', max_length=200)),
                ('Kuks', models.BooleanField(default=False, help_text='Squirrel was heard kukking, a chirpy vocal communication')),
                ('Quaas', models.BooleanField(default=False, help_text='Squirrel was heard quaaing, an elongated vocal communication')),
                ('Moans', models.BooleanField(default=False, help_text='Squirrel was heard moaning, a high-pitched vocal communication')),
                ('Tail_flags', models.BooleanField(default=False, help_text='Squirrel was seen flagging tail')),
                ('Tail_twitches', models.BooleanField(default=False, help_text='Squirrel was seen twitching tail')),
                ('Approaches', models.BooleanField(default=False, help_text='Squirrel was seen approaching human for food')),
                ('Indifferent', models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence')),
                ('Runs_from', models.BooleanField(default=False, help_text='Squirrel was seen running from humans')),
            ],
        ),
    ]
