# Generated by Django 2.2.7 on 2020-10-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20201015_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Latitude Coordinate for Squirrel sighting point', max_digits=20, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Longitude Coordinate for Squirrel sighting point', max_digits=20, max_length=50),
        ),
    ]
